name: Serenity BDD Tests with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Amazon Corretto 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x gradlew

      - name: Build the project
        run: ./gradlew build -x test --info

      - name: Run tests with Gradle
        run: ./gradlew clean test aggregate --info

      - name: Upload Serenity Report
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity

      - name: Deploy Serenity Report to GitHub Pages
        if: success()
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          # Clona la rama gh-pages o crea una nueva
          git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages || git clone --depth 1 https://github.com/${{ github.repository }} gh-pages
          cd gh-pages
          git checkout -b gh-pages || git checkout gh-pages

          # Borra contenido anterior y copia nuevo
          rm -rf ./*
          cp -r ../target/site/serenity/* ./

          # Commit y push
          git add .
          git commit -m "🚀 Update Serenity Report [skip ci]" || echo "Nothing to commit"
          git push origin gh-pages
