name: Serenity BDD Tests with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Amazon Corretto 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x gradlew

      - name: Build the project
        run: ./gradlew build -x test --info

      - name: Run tests with Gradle
        run: ./gradlew clean test aggregate --info

#      - name: Upload Serenity Report
#        uses: actions/upload-artifact@v3
#        with:
#          name: serenity-report
#          path: target/site/serenity
